project: sample-nodejs-webapp
description: A sample web application
appSpec:
  image: node
  version: 18
  env:
    - name: APP_PORT
      value: 3000
    - name: DB_HOST
      value: localhost
    - name: DB_PORT
      value: 5432
    - name: DB_NAME
      value: sampledb
    - name: DB_USER
      value: sampleuser
    - name: DB_PASSWORD
      value: mysecretpassword
databaseSpec:
  image: postgres
  version: 15
  env:
    - name: POSTGRES_USER
      value: sampleuser
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    - name: POSTGRES_DB
      value: sampledb
