project: sample-nodejs-webapp
description: A sample web application
appSpec:
  image: node
  version: 18.17
  env:
    DB_HOST: localhost
    DB_PORT: 5432
    DB_NAME: sampledb
    DB_USER: sampleuser
    DB_PASSWORD: mysecretpassword
databaseSpec:
  image: postgres
  version: 15
  env:
    POSTGRES_USER: sampleuser
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_DB : sampledb
