---
app_name: newsample02
app_owner: thainm2
description: A sample web application
frontend:
  image: node
  version: 18
  static_dir: dist
  env:
    API_URL: "https://uet.vn"
    SERVICE_NAME: "frontend"
# backend:
#   image: node
#   version: 16
database:
  image: postgres
